#
# Copyright (c) 2020 Legrand North America, LLC.
#
# SPDX-License-Identifier: MIT

# The west manifest file for upstream Zephyr Project's Zephyr repo.
#
# NOTE: Requires west 0.8.0a1 or later (pip3 install west==0.8.0a1)
#
# Usage (from top of workspace):
#   west
#     --zephyr-base zephyr
#     init
#       -m https://github.com/bacnet-stack/bacnet-stack
#       --mr <desired repo branch>
#       --mf zephyr/manifests/zp/zephyr/west.yml
#       --zephyr-base zephyr
#       $workspace
#   cd $workspace
#   west update
#   source zephyr/zephyr-env.sh

manifest:
  version: 0.7
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v2.3.0  # Latest integrated release
      import: true
      path: zephyr
  self:
      path: bacnet-stack
