/**
 * @file
 * @brief command line tool that sends a BACnet ConfirmedPrivateTransfer
 * message with one or more application values.
 * @author Steve Karg <skarg@users.sourceforge.net>
 * @date 2026
 * @copyright SPDX-License-Identifier: MIT
 */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#define PRINT_ENABLED 1
/* BACnet Stack defines - first */
#include "bacnet/bacdef.h"
/* BACnet Stack API */
#include "bacnet/bacapp.h"
#include "bacnet/bacerror.h"
#include "bacnet/bactext.h"
#include "bacnet/iam.h"
#include "bacnet/npdu.h"
#include "bacnet/apdu.h"
#include "bacnet/ptransfer.h"
#include "bacnet/version.h"
#include "bacnet/whois.h"
/* some demo stuff needed */
#include "bacnet/basic/binding/address.h"
#include "bacnet/basic/object/device.h"
#include "bacnet/basic/service/h_pt.h"
#include "bacnet/basic/service/h_pt_a.h"
#include "bacnet/basic/service/s_pt.h"
#include "bacnet/basic/sys/debug.h"
#include "bacnet/basic/sys/filename.h"
#include "bacnet/basic/sys/mstimer.h"
#include "bacnet/basic/services.h"
#include "bacnet/basic/tsm/tsm.h"
#include "bacnet/datalink/datalink.h"
#include "bacnet/datalink/dlenv.h"
#include "bacport.h"

#ifndef MAX_PROPERTY_VALUES
#define MAX_PROPERTY_VALUES 64
#endif

static uint8_t Rx_Buf[MAX_MPDU] = { 0 };
static uint32_t Target_Device_Object_Instance = BACNET_MAX_INSTANCE;
static uint16_t Target_Vendor_Identifier = 260;
static uint32_t Target_Service_Number = 0;
static BACNET_APPLICATION_DATA_VALUE
    Target_Object_Property_Value[MAX_PROPERTY_VALUES];
static BACNET_ADDRESS Target_Address;
static uint8_t Request_Invoke_ID = 0;
static bool Error_Detected = false;

/**
 * @brief Handle a confirmed private-transfer error response.
 * @param src Source BACnet address of the responder.
 * @param invoke_id Invoke ID of the matching request.
 * @param service_choice BACnet service choice for the error response.
 * @param service_request Buffer containing the encoded error service payload.
 * @param service_len Length of the service request in bytes.
 */
static void My_Private_Transfer_Error_Handler(
    BACNET_ADDRESS *src,
    uint8_t invoke_id,
    uint8_t service_choice,
    uint8_t *service_request,
    uint16_t service_len)
{
    BACNET_ERROR_CLASS error_class = ERROR_CLASS_DEVICE;
    BACNET_ERROR_CODE error_code = ERROR_CODE_OTHER;
    BACNET_PRIVATE_TRANSFER_DATA private_data = { 0 };
    int len = 0;

    (void)service_choice;
    if (address_match(&Target_Address, src) &&
        (invoke_id == Request_Invoke_ID)) {
        len = ptransfer_error_decode_service_request(
            service_request, service_len, &error_class, &error_code,
            &private_data);
        if (len > 0) {
            printf(
                "BACnet Error: %s: %s\n",
                bactext_error_class_name((int)error_class),
                bactext_error_code_name((int)error_code));
            printf(
                "PrivateTransfer: vendorID=%u serviceNumber=%lu\n",
                (unsigned)private_data.vendorID,
                (unsigned long)private_data.serviceNumber);
        }
        Error_Detected = true;
    }
}

/**
 * @brief Handle an abort response for the current private-transfer request.
 * @param src Source BACnet address of the responder.
 * @param invoke_id Invoke ID of the matching request.
 * @param abort_reason BACnet abort reason code.
 * @param server True if the abort was generated by a server.
 */
static void My_Abort_Handler(
    BACNET_ADDRESS *src, uint8_t invoke_id, uint8_t abort_reason, bool server)
{
    (void)server;
    if (address_match(&Target_Address, src) &&
        (invoke_id == Request_Invoke_ID)) {
        printf(
            "BACnet Abort: %s\n", bactext_abort_reason_name((int)abort_reason));
        Error_Detected = true;
    }
}

/**
 * @brief Handle a reject response for the current private-transfer request.
 * @param src Source BACnet address of the responder.
 * @param invoke_id Invoke ID of the matching request.
 * @param reject_reason BACnet reject reason code.
 */
static void
My_Reject_Handler(BACNET_ADDRESS *src, uint8_t invoke_id, uint8_t reject_reason)
{
    if (address_match(&Target_Address, src) &&
        (invoke_id == Request_Invoke_ID)) {
        printf(
            "BACnet Reject: %s\n",
            bactext_reject_reason_name((int)reject_reason));
        Error_Detected = true;
    }
}

/**
 * @brief Handle a confirmed private-transfer ACK response.
 * @param service_request Buffer containing the encoded ACK payload.
 * @param service_len Length of the service request in bytes.
 * @param src Source BACnet address of the responder.
 * @param service_data Confirmed service ACK metadata from the APDU header.
 */
static void My_Private_Transfer_Ack_Handler(
    uint8_t *service_request,
    uint16_t service_len,
    BACNET_ADDRESS *src,
    BACNET_CONFIRMED_SERVICE_ACK_DATA *service_data)
{
    int len = 0;
    BACNET_PRIVATE_TRANSFER_DATA data;

    if (address_match(&Target_Address, src) &&
        (service_data->invoke_id == Request_Invoke_ID)) {
        len = ptransfer_decode_service_request(
            service_request, service_len, &data);
        if (len < 0) {
            printf("<decode failed!>\n");
        } else {
            private_transfer_print_data(&data);
        }
    }
}

/**
 * @brief Configure the BACnet service callbacks used by the client.
 */
static void Init_Service_Handlers(void)
{
    Device_Init(NULL);
    apdu_set_unconfirmed_handler(SERVICE_UNCONFIRMED_WHO_IS, handler_who_is);
    apdu_set_unconfirmed_handler(SERVICE_UNCONFIRMED_I_AM, handler_i_am_bind);
    apdu_set_unrecognized_service_handler_handler(handler_unrecognized_service);
    apdu_set_confirmed_handler(
        SERVICE_CONFIRMED_READ_PROPERTY, handler_read_property);
    /* application specific handling */
    apdu_set_confirmed_ack_handler(
        SERVICE_CONFIRMED_PRIVATE_TRANSFER, My_Private_Transfer_Ack_Handler);
    apdu_set_complex_error_handler(
        SERVICE_CONFIRMED_PRIVATE_TRANSFER, My_Private_Transfer_Error_Handler);
    apdu_set_abort_handler(My_Abort_Handler);
    apdu_set_reject_handler(My_Reject_Handler);
}

/**
 * @brief Print the command-line usage for the ptransfer client.
 * @param filename Program name to display in the usage text.
 */
static void print_usage(const char *filename)
{
    printf(
        "Usage: %s device-instance vendor-id service-number tag value "
        "[tag value...]\n",
        filename);
    printf("       [--dnet][--dadr][--mac][--debug]\n");
    printf("       [--version][--help]\n");
}

/**
 * @brief Print the detailed help text for the ptransfer client.
 * @param filename Program name to display in the examples.
 */
static void print_help(const char *filename)
{
    printf("Send a BACnet ConfirmedPrivateTransfer with one or more values.\n");
    printf("--mac A\n"
           "Optional BACnet mac address."
           "Valid ranges are from 00 to FF (hex) for MS/TP or ARCNET,\n"
           "or an IP string with optional port number like 10.1.2.3:47808\n"
           "or an Ethernet MAC in hex like 00:21:70:7e:32:bb\n");
    printf("\n");
    printf("--dnet N\n"
           "Optional BACnet network number N for directed requests.\n"
           "Valid range is from 0 to 65535 where 0 is the local connection\n"
           "and 65535 is network broadcast.\n");
    printf("\n");
    printf("--dadr A\n"
           "Optional BACnet mac address on the destination BACnet network "
           "number.\n"
           "Valid ranges are from 00 to FF (hex) for MS/TP or ARCNET,\n"
           "or an IP string with optional port number like 10.1.2.3:47808\n"
           "or an Ethernet MAC in hex like 00:21:70:7e:32:bb\n");
    printf("\n");
    printf("--debug S\n"
           "Optional debug severity level 0=emergency, 1=alert, 2=critical,\n"
           "3=error, 4=warning, 5=notice, 6=info, 7=debug, -1=disable.\n");
    printf("\n");
    printf("device-instance:\n"
           "BACnet Device Object Instance number that you are\n"
           "trying to communicate with.\n");
    printf("vendor-id:\n"
           "The specific vendor ID for the proprietary service.\n");
    printf("service-number:\n"
           "The vendor-defined private service number.\n");
    printf("tag:\n"
           "BACNET_APPLICATION_TAG value for the data item.\n");
    printf("value:\n"
           "ASCII representation of the payload value to encode.\n");
    printf(
        "Example:\n"
        "%s 99 260 23 4 1.1 2 42\n",
        filename);
}

/**
 * @brief Send a BACnet confirmed private transfer with one or more values.
 * @param argc Number of command-line arguments.
 * @param argv Command-line arguments.
 * @return 0 on success, 1 on error.
 */
int main(int argc, char *argv[])
{
    BACNET_ADDRESS src = { 0 };
    uint16_t pdu_len = 0;
    unsigned timeout = 100;
    unsigned max_apdu = 0;
    unsigned timeout_milliseconds = 0;
    bool found = false;
    const char *filename = NULL;
    char *value_string = NULL;
    struct mstimer apdu_timer = { 0 };
    struct mstimer datalink_timer = { 0 };
    bool status = false;
    int argi = 0;
    long dnet = -1;
    uint32_t severity = 0;
    BACNET_MAC_ADDRESS mac = { 0 };
    BACNET_MAC_ADDRESS adr = { 0 };
    BACNET_ADDRESS dest = { 0 };
    bool specific_address = false;
    unsigned target_args = 0;
    unsigned property_count = 0;
    int tag_value_arg = 0;
    BACNET_APPLICATION_TAG property_tag;
    uint8_t context_tag = 0;
    uint8_t tx_buffer[MAX_APDU] = { 0 };

    filename = filename_remove_path(argv[0]);
    for (argi = 1; argi < argc; argi++) {
        if (strcmp(argv[argi], "--help") == 0) {
            print_usage(filename);
            print_help(filename);
            return 0;
        }
        if (strcmp(argv[argi], "--version") == 0) {
            printf("%s %s\n", filename, BACNET_VERSION_TEXT);
            printf("Copyright (C) 2026 by Steve Karg and others.\n"
                   "This is free software; see the source for copying "
                   "conditions.\n"
                   "There is NO warranty; not even for MERCHANTABILITY or\n"
                   "FITNESS FOR A PARTICULAR PURPOSE.\n");
            return 0;
        }
        if (strcmp(argv[argi], "--mac") == 0) {
            if (++argi < argc) {
                if (bacnet_address_mac_from_ascii(&mac, argv[argi])) {
                    specific_address = true;
                }
            }
        } else if (strcmp(argv[argi], "--dnet") == 0) {
            if (++argi < argc) {
                if (!bacnet_strtol(argv[argi], &dnet)) {
                    fprintf(stderr, "dnet=%s invalid\n", argv[argi]);
                    return 1;
                }
                if ((dnet >= 0) && (dnet <= BACNET_BROADCAST_NETWORK)) {
                    specific_address = true;
                }
            }
        } else if (strcmp(argv[argi], "--dadr") == 0) {
            if (++argi < argc) {
                if (bacnet_address_mac_from_ascii(&adr, argv[argi])) {
                    specific_address = true;
                }
            }
        } else if (strcmp(argv[argi], "--debug") == 0) {
            if (++argi < argc) {
                if (bactext_debug_severity_strtol(argv[argi], &severity)) {
                    debug_log_severity_set(severity);
                } else {
                    debug_log_severity_set(DEBUG_LOG_DISABLED);
                }
            }
        } else if (target_args == 0) {
            Target_Device_Object_Instance = strtol(argv[argi], NULL, 0);
            target_args++;
        } else if (target_args == 1) {
            Target_Vendor_Identifier = strtol(argv[argi], NULL, 0);
            target_args++;
        } else if (target_args == 2) {
            Target_Service_Number = strtol(argv[argi], NULL, 0);
            target_args++;
        } else {
            if (property_count >= MAX_PROPERTY_VALUES) {
                fprintf(
                    stderr, "Error: Exceeded %d tag-value pairs.\n",
                    MAX_PROPERTY_VALUES);
                return 1;
            }
            if (toupper(argv[argi][0]) == 'C') {
                context_tag = strtol(&argv[argi][1], NULL, 0);
                tag_value_arg = argi + 1;
                Target_Object_Property_Value[property_count].context_tag =
                    context_tag;
                Target_Object_Property_Value[property_count].context_specific =
                    true;
                argi++;
            } else {
                tag_value_arg = argi;
                Target_Object_Property_Value[property_count].context_specific =
                    false;
            }
            property_tag = strtol(argv[tag_value_arg], NULL, 0);
            if (tag_value_arg + 1 >= argc) {
                fprintf(stderr, "Error: not enough tag-value pairs\n");
                return 1;
            }
            value_string = argv[tag_value_arg + 1];
            if (property_tag >= MAX_BACNET_APPLICATION_TAG) {
                fprintf(
                    stderr, "Error: tag=%u - it must be less than %u\n",
                    property_tag, MAX_BACNET_APPLICATION_TAG);
                return 1;
            }
            status = bacapp_parse_application_data(
                property_tag, value_string,
                &Target_Object_Property_Value[property_count]);
            if (!status) {
                fprintf(stderr, "Error: unable to parse the tag value\n");
                return 1;
            }
            Target_Object_Property_Value[property_count].next = NULL;
            if (property_count > 0) {
                Target_Object_Property_Value[property_count - 1].next =
                    &Target_Object_Property_Value[property_count];
            }
            property_count++;
            if (tag_value_arg == argi) {
                argi++;
            }
        }
    }
    if ((target_args < 3) || (property_count == 0)) {
        print_usage(filename);
        return 0;
    }
    if (Target_Device_Object_Instance > BACNET_MAX_INSTANCE) {
        fprintf(
            stderr, "device-instance=%u - not greater than %u\n",
            Target_Device_Object_Instance, BACNET_MAX_INSTANCE);
        return 1;
    }
    Device_Set_Object_Instance_Number(BACNET_MAX_INSTANCE);
    address_init();
    if (specific_address) {
        if ((dnet < 0) || (dnet > BACNET_BROADCAST_NETWORK)) {
            dnet = BACNET_BROADCAST_NETWORK;
        }
        bacnet_address_init(&dest, &mac, dnet, &adr);
        address_add(Target_Device_Object_Instance, MAX_APDU, &dest);
    }
    Init_Service_Handlers();
    dlenv_init();
    atexit(datalink_cleanup);
    mstimer_init();
    timeout_milliseconds = apdu_timeout() * apdu_retries();
    mstimer_set(&apdu_timer, timeout_milliseconds);
    mstimer_set(&datalink_timer, 1000);

    found = address_bind_request(
        Target_Device_Object_Instance, &max_apdu, &Target_Address);
    if (!found) {
        Send_WhoIs(
            Target_Device_Object_Instance, Target_Device_Object_Instance);
    }

    for (;;) {
        pdu_len = datalink_receive(&src, &Rx_Buf[0], MAX_MPDU, timeout);
        if (pdu_len) {
            npdu_handler(&src, &Rx_Buf[0], pdu_len);
        }
        if (Error_Detected) {
            break;
        }
        if (!found) {
            found = address_bind_request(
                Target_Device_Object_Instance, &max_apdu, &Target_Address);
        }
        if (found) {
            if (Request_Invoke_ID == 0) {
                Request_Invoke_ID = Send_Private_Transfer_Request(
                    &tx_buffer[0], sizeof(tx_buffer),
                    Target_Device_Object_Instance, Target_Vendor_Identifier,
                    Target_Service_Number, &Target_Object_Property_Value[0]);
            } else if (tsm_invoke_id_free(Request_Invoke_ID)) {
                break;
            } else if (tsm_invoke_id_failed(Request_Invoke_ID)) {
                fprintf(stderr, "\rError: TSM Timeout!\n");
                tsm_free_invoke_id(Request_Invoke_ID);
                Error_Detected = true;
                /* try again or abort? */
                break;
            }
        } else if (mstimer_expired(&apdu_timer)) {
            /* increment timer - exit if timed out */
            printf("\rError: APDU Timeout!\n");
            Error_Detected = true;
            break;
        }
        if (mstimer_expired(&datalink_timer)) {
            datalink_maintenance_timer(
                mstimer_interval(&datalink_timer) / 1000);
            mstimer_reset(&datalink_timer);
        }
    }
    if (Error_Detected) {
        return 1;
    }
    return 0;
}
