; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stamplc-mstp

[wifi_common]
build_flags =
    -DWIFI_SSID=\"REPLACE_WITH_WIFI_SSID\"
    -DWIFI_PASS=\"REPLACE_WITH_WIFI_PASSWORD\"

[bip_common]
build_flags =
    -UBACDL_MSTP
    -DBACDL_BIP
    -DBACNET_IP_PORT=47808
    -DMAX_APDU=1476

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:extra_script.py
lib_deps =
    m5stack/M5StamPLC@^1.2.0
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu11
    -std=gnu++17
    -I src
    -I ../../src
    -DBACDL_MSTP
    -DMAX_TSM_TRANSACTIONS=1
    -DPRINT_ENABLED=0
    -DBACNET_BIG_ENDIAN=0
    -DCRC_USE_TABLE
    -DBACAPP_MINIMAL
    -DBACAPP_TIMESTAMP
    -DBACNET_STACK_DEPRECATED_DISABLE
    -DBACNET_PROTOCOL_REVISION=16
    -DCONFIG_BACNET_BASIC_OBJECT_ANALOG_INPUT
    -DCONFIG_BACNET_BASIC_OBJECT_BINARY_INPUT
    -DCONFIG_BACNET_BASIC_OBJECT_BINARY_OUTPUT

[env:m5stamplc-mstp]
board = m5stamplc
build_flags =
    ${env.build_flags}
    -DMAX_APDU=480
build_src_filter =
    +<main.cpp>
    +<bacnet_app.c>
    +<mstimer_init.c>
    +<rs485.c>
    +<dlenv.c>
lib_deps = m5stack/M5StamPLC@^1.2.0

[env:m5stamplc-bip]
board = m5stamplc
build_flags =
    ${env.build_flags}
    ${bip_common.build_flags}
    ${wifi_common.build_flags}
    -DUSE_M5STAMPLC_IO=1
build_src_filter =
    +<main_bip.cpp>
    +<bacnet_app.c>
    +<bip.c>
    +<bip_init.c>
    +<bvlc.c>
    +<bip_socket.cpp>
    +<mstimer_init.c>
lib_deps = m5stack/M5StamPLC@^1.2.0

[env:esp32-poe-wifi-bip]
board = esp32-poe
build_flags =
    ${env.build_flags}
    ${bip_common.build_flags}
    ${wifi_common.build_flags}
    -DUSE_M5STAMPLC_IO=0
    -DUSE_ETH_INTERFACE=0
build_src_filter =
    +<main_bip.cpp>
    +<bacnet_app.c>
    +<bip.c>
    +<bip_init.c>
    +<bvlc.c>
    +<bip_socket.cpp>
    +<mstimer_init.c>
lib_deps =

[env:esp32-poe-eth-bip]
board = esp32-poe
build_flags =
    ${env.build_flags}
    ${bip_common.build_flags}
    -DUSE_M5STAMPLC_IO=0
    -DUSE_ETH_INTERFACE=1
build_src_filter =
    +<main_bip.cpp>
    +<bacnet_app.c>
    +<bip.c>
    +<bip_init.c>
    +<bvlc.c>
    +<bip_socket.cpp>
    +<mstimer_init.c>
lib_deps =

[env:xiao-esp32c3-wifi-bip]
board = seeed_xiao_esp32c3
build_flags =
    ${env.build_flags}
    ${bip_common.build_flags}
    ${wifi_common.build_flags}
    -DUSE_M5STAMPLC_IO=0
    -DUSE_ETH_INTERFACE=0
build_src_filter =
    +<main_bip.cpp>
    +<bacnet_app.c>
    +<bip.c>
    +<bip_init.c>
    +<bvlc.c>
    +<bip_socket.cpp>
    +<mstimer_init.c>
lib_deps =

[env:m5stamplc-gateway-bip-mstp]
board = m5stamplc
build_flags =
    ${env.build_flags}
    ${wifi_common.build_flags}
    -DMAX_APDU=480
    -UBACDL_MSTP
    -DBACDL_MSTP
    -DBACDL_BIP
    -DBACNET_IP_PORT=47808
    -DROUTER_BIP_NET=1
    -DROUTER_MSTP_NET=200
    -DROUTER_MSTP_MAC=2
build_src_filter =
    +<main_gateway_router.cpp>
    +<bacnet_app.c>
    +<bip.c>
    +<bip_init.c>
    +<bvlc.c>
    +<bip_socket.cpp>
    +<mstimer_init.c>
    +<rs485.c>
    +<dlenv.c>
lib_deps = m5stack/M5StamPLC@^1.2.0
