/*####COPYRIGHTBEGIN####
 -------------------------------------------
 Copyright (C) 2005 John Goulah

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to 
 The Free Software Foundation, Inc.
 59 Temple Place - Suite 330 
 Boston, MA  02111-1307, USA.

 As a special exception, if other files instantiate templates or
 use macros or inline functions from this file, or you compile
 this file and link it with other works to produce a work based
 on this file, this file does not by itself cause the resulting
 work to be covered by the GNU General Public License. However
 the source code for this file must still be made available in
 accordance with section (3) of the GNU General Public License.

 This exception does not invalidate any other reasons why a work
 based on this file might be covered by the GNU General Public
 License.
 -------------------------------------------
####COPYRIGHTEND####*/
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include "bacprop.h"

/* Informations from table K-X4. Minimum Character-String Lengths */
PROP_MINIMUM_LENGTH bacnet_property_minimum_character_string_length[] = {
    {PROP_ACTION_TEXT, 32}
    ,
    {PROP_APPLICATION_SOFTWARE_VERSION, 64}
    ,
    {PROP_DESCRIPTION, 255}
    ,
    {PROP_DESCRIPTION_OF_HALT, 64}
    ,
    {PROP_DEVICE_TYPE, 64}
    ,
    {PROP_FILE_TYPE, 32}
    ,
    {PROP_FIRMWARE_REVISION, 64}
    ,
    {PROP_INACTIVE_TEXT, 32}
    ,
    {PROP_ACTIVE_TEXT, 32}
    ,
    {PROP_INSTANCE_OF, 64}
    ,
    {PROP_LOCATION, 64}
    ,
    {PROP_MODEL_NAME, 64}
    ,
    {PROP_OBJECT_NAME, 64}
    ,
    {PROP_PROFILE_NAME, 64}
    ,
    {PROP_STATE_TEXT, 32}
    ,
    {PROP_VENDOR_NAME, 64}
    ,
    {-1, 32}    /* All other character string properties */
};

PROP_TAG_DATA bacnet_object_device_property_tag_map[] = {
    /* Very-Generic */
    {-1, PROP_OBJECT_IDENTIFIER, BACNET_APPLICATION_TAG_OBJECT_ID}
    ,
    {-1, PROP_OBJECT_NAME, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {-1, PROP_OBJECT_TYPE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {-1, PROP_PROFILE_NAME, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {-1, PROP_LOCATION, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {-1, PROP_DESCRIPTION, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {-1, PROP_EVENT_TIME_STAMPS, BACNET_APPLICATION_TAG_TIMESTAMP}
    ,

    /* Generic */
    {-1, PROP_STATUS_FLAGS, BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {-1, PROP_EVENT_STATE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {-1, PROP_RELIABILITY, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {-1, PROP_OUT_OF_SERVICE, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    /* Generic with intrinsic reporting */
    {-1, PROP_TIME_DELAY, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {-1, PROP_NOTIFICATION_CLASS, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {-1, PROP_ALARM_VALUE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {-1, PROP_EVENT_ENABLE, BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {-1, PROP_ACKED_TRANSITIONS, BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {-1, PROP_NOTIFY_TYPE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,

    /* Specific to devices */
    {OBJECT_DEVICE, PROP_SYSTEM_STATUS, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_DEVICE, PROP_VENDOR_NAME, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_DEVICE, PROP_VENDOR_IDENTIFIER, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_MODEL_NAME, BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_DEVICE, PROP_FIRMWARE_REVISION,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_DEVICE, PROP_APPLICATION_SOFTWARE_VERSION,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_DEVICE, PROP_PROTOCOL_VERSION, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_PROTOCOL_CONFORMANCE_CLASS,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_PROTOCOL_REVISION, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_PROTOCOL_SERVICES_SUPPORTED,
        BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {OBJECT_DEVICE, PROP_PROTOCOL_OBJECT_TYPES_SUPPORTED,
        BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {OBJECT_DEVICE, PROP_MAX_APDU_LENGTH_ACCEPTED,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_SEGMENTATION_SUPPORTED,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_DEVICE, PROP_APDU_TIMEOUT, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_NUMBER_OF_APDU_RETRIES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_LOCAL_DATE, BACNET_APPLICATION_TAG_DATE}
    ,
    {OBJECT_DEVICE, PROP_LOCAL_TIME, BACNET_APPLICATION_TAG_TIME}
    ,
    {OBJECT_DEVICE, PROP_UTC_OFFSET, BACNET_APPLICATION_TAG_SIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_DAYLIGHT_SAVINGS_STATUS,
        BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    {OBJECT_DEVICE, PROP_ALIGN_INTERVALS, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    {OBJECT_DEVICE, PROP_INTERVAL_OFFSET, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_DEVICE, PROP_TIME_SYNCHRONIZATION_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,

    {OBJECT_ANALOG_INPUT, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_UPDATE_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ANALOG_INPUT, PROP_UNITS, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_ANALOG_INPUT, PROP_MIN_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_MAX_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_RESOLUTION, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_COV_INCREMENT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_HIGH_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_LOW_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_DEADBAND, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_INPUT, PROP_LIMIT_ENABLE, BACNET_APPLICATION_TAG_BIT_STRING}
    ,

    {OBJECT_ANALOG_OUTPUT, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_REAL,
        true}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_UPDATE_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_UNITS, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_MIN_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_MAX_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_RESOLUTION, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_COV_INCREMENT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_HIGH_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_LOW_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_DEADBAND, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_LIMIT_ENABLE, BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_RELINQUISH_DEFAULT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_OUTPUT, PROP_PRIORITY_ARRAY, BACNET_APPLICATION_TAG_REAL}
    ,

    {OBJECT_ANALOG_VALUE, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_REAL, true}
    ,
    {OBJECT_ANALOG_VALUE, PROP_UPDATE_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ANALOG_VALUE, PROP_UNITS, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_ANALOG_VALUE, PROP_MIN_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_MAX_PRES_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_RESOLUTION, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_COV_INCREMENT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_HIGH_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_LOW_LIMIT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_DEADBAND, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_LIMIT_ENABLE, BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    {OBJECT_ANALOG_VALUE, PROP_RELINQUISH_DEFAULT, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_ANALOG_VALUE, PROP_PRIORITY_ARRAY, BACNET_APPLICATION_TAG_REAL}
    ,

    {OBJECT_BINARY_INPUT, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_INPUT, PROP_POLARITY, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_INPUT, PROP_INACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_INPUT, PROP_ACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_INPUT, PROP_CHANGE_OF_STATE_COUNT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_INPUT, PROP_CHANGE_OF_STATE_TIME,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_INPUT, PROP_TIME_OF_ACTIVE_TIME_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_INPUT, PROP_TIME_OF_STATE_COUNT_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_INPUT, PROP_ELAPSED_ACTIVE_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,

    {OBJECT_BINARY_OUTPUT, PROP_PRESENT_VALUE,
        BACNET_APPLICATION_TAG_ENUMERATED, true}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_POLARITY, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_INACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_ACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_CHANGE_OF_STATE_COUNT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_CHANGE_OF_STATE_TIME,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_TIME_OF_ACTIVE_TIME_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_TIME_OF_STATE_COUNT_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_ELAPSED_ACTIVE_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_RELINQUISH_DEFAULT,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_MINIMUM_OFF_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_MINIMUM_ON_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_FEEDBACK_VALUE,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_OUTPUT, PROP_PRIORITY_ARRAY,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,

    {OBJECT_BINARY_VALUE, PROP_PRESENT_VALUE,
        BACNET_APPLICATION_TAG_ENUMERATED, true}
    ,
    {OBJECT_BINARY_VALUE, PROP_POLARITY, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_VALUE, PROP_INACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_VALUE, PROP_ACTIVE_TEXT,
        BACNET_APPLICATION_TAG_CHARACTER_STRING}
    ,
    {OBJECT_BINARY_VALUE, PROP_CHANGE_OF_STATE_COUNT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_VALUE, PROP_CHANGE_OF_STATE_TIME,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_VALUE, PROP_TIME_OF_ACTIVE_TIME_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_VALUE, PROP_TIME_OF_STATE_COUNT_RESET,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_BINARY_VALUE, PROP_ELAPSED_ACTIVE_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_VALUE, PROP_RELINQUISH_DEFAULT,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_BINARY_VALUE, PROP_MINIMUM_OFF_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_VALUE, PROP_MINIMUM_ON_TIME,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_BINARY_VALUE, PROP_PRIORITY_ARRAY,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,

    {OBJECT_CALENDAR, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    /* DATE_LIST */

    {OBJECT_EVENT_ENROLLMENT, PROP_EVENT_TYPE,
        BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    /* ObjectPropertyReference */

    {OBJECT_MULTI_STATE_INPUT, PROP_PRESENT_VALUE,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_INPUT, PROP_NUMBER_OF_STATES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    /* PROP_STATE_TEXT */

    {OBJECT_MULTI_STATE_OUTPUT, PROP_PRESENT_VALUE,
        BACNET_APPLICATION_TAG_UNSIGNED_INT, true}
    ,
    {OBJECT_MULTI_STATE_OUTPUT, PROP_NUMBER_OF_STATES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_OUTPUT, PROP_RELINQUISH_DEFAULT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_OUTPUT, PROP_FEEDBACK_VALUE,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_OUTPUT, PROP_PRIORITY_ARRAY,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,

    {OBJECT_MULTI_STATE_VALUE, PROP_PRESENT_VALUE,
        BACNET_APPLICATION_TAG_UNSIGNED_INT, true}
    ,
    {OBJECT_MULTI_STATE_VALUE, PROP_NUMBER_OF_STATES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_VALUE, PROP_RELINQUISH_DEFAULT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_MULTI_STATE_VALUE, PROP_PRIORITY_ARRAY,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,

    {OBJECT_NOTIFICATION_CLASS, PROP_ACK_REQUIRED,
        BACNET_APPLICATION_TAG_BIT_STRING}
    ,
    /* PROP_PRIORITY */
    /* RECIPIENT_LIST */

    {OBJECT_SCHEDULE, PROP_PRIORITY_FOR_WRITING,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_SCHEDULE, PROP_EFFECTIVE_PERIOD, BACNET_APPLICATION_TAG_DATERANGE}
    ,

    {OBJECT_TRENDLOG, PROP_ENABLE, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    {OBJECT_TRENDLOG, PROP_START_TIME, BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_TRENDLOG, PROP_STOP_TIME, BACNET_APPLICATION_TAG_DATETIME}
    ,
    /*{ OBJECT_TRENDLOG,             PROP_LOG_DEVICE_OBJECT */
    {OBJECT_TRENDLOG, PROP_LOG_INTERVAL, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_COV_RESUBSCRIPTION_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_CLIENT_COV_INCREMENT, BACNET_APPLICATION_TAG_REAL}
    ,   /* HACK */
    {OBJECT_TRENDLOG, PROP_STOP_WHEN_FULL, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    {OBJECT_TRENDLOG, PROP_BUFFER_SIZE, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    /*{ OBJECT_TRENDLOG,             PROP_LOG_BUFFER */
    {OBJECT_TRENDLOG, PROP_RECORD_COUNT, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_TOTAL_RECORD_COUNT,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_NOTIFICATION_THRESHOLD,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_RECORDS_SINCE_NOTIFICATION,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_LAST_NOTIFY_RECORD,
        BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_LOGGING_TYPE, BACNET_APPLICATION_TAG_ENUMERATED}
    ,
    {OBJECT_TRENDLOG, PROP_ALIGN_INTERVALS, BACNET_APPLICATION_TAG_BOOLEAN}
    ,
    {OBJECT_TRENDLOG, PROP_INTERVAL_OFFSET, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TRENDLOG, PROP_TRIGGER, BACNET_APPLICATION_TAG_BOOLEAN}
    ,

    {OBJECT_AVERAGING, PROP_MAXIMUM_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_AVERAGING, PROP_MINIMUM_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_AVERAGING, PROP_AVERAGE_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_AVERAGING, PROP_VARIANCE_VALUE, BACNET_APPLICATION_TAG_REAL}
    ,
    {OBJECT_AVERAGING, PROP_MAXIMUM_VALUE_TIMESTAMP,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_AVERAGING, PROP_MINIMUM_VALUE_TIMESTAMP,
        BACNET_APPLICATION_TAG_DATETIME}
    ,
    {OBJECT_AVERAGING, PROP_ATTEMPTED_SAMPLES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT, true}
    ,
    {OBJECT_AVERAGING, PROP_VALID_SAMPLES, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_AVERAGING, PROP_WINDOW_INTERVAL,
        BACNET_APPLICATION_TAG_UNSIGNED_INT, true}
    ,
    {OBJECT_AVERAGING, PROP_WINDOW_SAMPLES,
        BACNET_APPLICATION_TAG_UNSIGNED_INT, true}
    ,

    {OBJECT_COMMAND, PROP_PRESENT_VALUE, BACNET_APPLICATION_TAG_UNSIGNED_INT,
        true}
    ,

    {-1, PROP_LOG_DEVICE_OBJECT_PROPERTY,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetDeviceObjectPropertyReference */
    {-1, PROP_OBJECT_PROPERTY_REFERENCE,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetDeviceObjectPropertyReference */
    {-1, PROP_LIST_OF_OBJECT_PROPERTY_REFERENCES,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetDeviceObjectPropertyReference */
    {-1, PROP_BELONGS_TO, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_LAST_ACCESS_POINT,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ACCOMPANIED, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_MEMBERS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_CREDENTIALS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_MEMBER_OF, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ZONE_MEMBERS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_DOOR_MEMBERS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_SUBORDINATE_LIST, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ACCESS_EVENT_CREDENTIAL,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ACCESS_DOORS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ZONE_TO, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ZONE_FROM, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_CREDENTIALS_IN_ZONE,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_LAST_CREDENTIAL_ADDED,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_LAST_CREDENTIAL_REMOVED,
        BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE, false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_ENTRY_POINTS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_EXIT_POINTS, BACNET_APPLICATION_TAG_DEVICE_OBJECT_REFERENCE,
        false}
    ,   /* BACnetDeviceObjectReference */
    {-1, PROP_MANIPULATED_VARIABLE_REFERENCE,
        BACNET_APPLICATION_TAG_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetObjectPropertyReference */
    {-1, PROP_CONTROLLED_VARIABLE_REFERENCE,
        BACNET_APPLICATION_TAG_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetObjectPropertyReference */
    {-1, PROP_INPUT_REFERENCE,
        BACNET_APPLICATION_TAG_OBJECT_PROPERTY_REFERENCE, false}
    ,   /* BACnetObjectPropertyReference */
    {-1, PROP_RECIPIENT_LIST, BACNET_APPLICATION_TAG_DESTINATION, false}
    ,   /* BACnetDestination (Recipient_List) */
    {-1, PROP_TIME_SYNCHRONIZATION_RECIPIENTS,
        BACNET_APPLICATION_TAG_RECIPIENT, false}
    ,   /* BACnetRecipient */
    {-1, PROP_UTC_TIME_SYNCHRONIZATION_RECIPIENTS,
        BACNET_APPLICATION_TAG_RECIPIENT, false}
    ,   /* BACnetRecipient */
    {-1, PROP_RESTART_NOTIFICATION_RECIPIENTS,
        BACNET_APPLICATION_TAG_RECIPIENT, false}
    ,   /* BACnetRecipient */
    {-1, PROP_ACTIVE_COV_SUBSCRIPTIONS,
        BACNET_APPLICATION_TAG_COV_SUBSCRIPTION, false}
    ,   /* BACnetCOVSubscription */
    {-1, PROP_DATE_LIST, BACNET_APPLICATION_TAG_CALENDAR_ENTRY, false}
    ,   /* BACnetCalendarEntry */
    {-1, PROP_WEEKLY_SCHEDULE, BACNET_APPLICATION_TAG_WEEKLY_SCHEDULE, false}
    ,   /* BACnetWeeklySchedule */
    {-1, PROP_EXCEPTION_SCHEDULE, BACNET_APPLICATION_TAG_SPECIAL_EVENT, false}
    ,   /* BACnetSpecialEvent */

    /* Non renseigné */
    {OBJECT_COMMAND, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_FILE, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_GROUP, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_LOOP, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_PROGRAM, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_LIFE_SAFETY_POINT, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_LIFE_SAFETY_ZONE, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCUMULATOR, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_PULSE_CONVERTER, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_EVENT_LOG, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_GLOBAL_GROUP, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_TREND_LOG_MULTIPLE, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_LOAD_CONTROL, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_STRUCTURED_VIEW, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_DOOR, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_LIGHTING_OUTPUT, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_CREDENTIAL, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_POINT, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_RIGHTS, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_USER, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,
    {OBJECT_ACCESS_ZONE, -1, BACNET_APPLICATION_TAG_UNSIGNED_INT}
    ,

    {-1, -1, -1}
};

signed bacprop_property_tag(
    BACNET_OBJECT_TYPE type,
    signed prop)
{
    PROP_TAG_DATA *ptag = &bacnet_object_device_property_tag_map[0];

    /* tag_id : -1 has no particular meaning : exit now ! */
    for (; ptag && ptag->tag_id != -1; ptag++)
        /* object_id : -1 means 'joker' */
        if (ptag->object_id == -1 || ptag->object_id == type)
            if (ptag->prop_id == prop)
                return ptag->tag_id;
    return -1;
}

bool bacprop_property_tag_writeable(
    BACNET_OBJECT_TYPE type,
    signed prop)
{
    PROP_TAG_DATA *ptag = &bacnet_object_device_property_tag_map[0];

    /* tag_id : -1 has no particular meaning : exit now ! */
    for (; ptag && ptag->tag_id != -1; ptag++)
        /* object_id : -1 means 'joker' */
        if (ptag->object_id == -1 || ptag->object_id == type)
            if (ptag->prop_id == prop)
                return ptag->writable;
    return false;
}

/*/ Returns minimum recommended character-string length for displaying properties */
int bacprop_minimum_character_string_length(
    signed prop)
{
    int i = 0;
    while (bacnet_property_minimum_character_string_length[i].PropertyId !=
        prop &&
        bacnet_property_minimum_character_string_length[i].PropertyId != -1)
        i++;
    return bacnet_property_minimum_character_string_length[i].MinimumLength;
}
